### ISSUE TITLE
Add Yoruba to the supported languages

### ISSUE THREAD

**Issue by smyja** [Sayad-Uddin-Tahsin/BBC-News-API#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sayad-Uddin-Tahsin** [comment]
@smyja, Thanks for your suggestion and letting me know! I've just committed changes on [`56af8dc`](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/commit/56af8dc7a20d444e638c1fe91fe7a3982961d4ac). From now on, you can use the BBC News API to get news in Yoruba. This endpoint will respond with news from [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba).

<a href="https://bbc-api.vercel.app/news?lang=yoruba"><img src="https://img.shields.io/website?url=https%3A%2F%2Fbbc-api.vercel.app%2Fnews?lang=yoruba&up_message=Online&down_message=Offline&label=Yoruba/News"></a> <a href="https://bbc-api.vercel.app/news?lang=yoruba"><img src="https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fbbc-api.vercel.app%2Fnews%3Flang%3Dyoruba&query=%24%5B'elapsed%20time'%5D&label=Latency"></a>

<a href="https://bbc-api.vercel.app/latest?lang=yoruba"><img src="https://img.shields.io/website?url=https%3A%2F%2Fbbc-api.vercel.app%2Flatest?lang=yoruba&up_message=Online&down_message=Offline&label=Yoruba/Latest"></a> <a href="https://bbc-api.vercel.app/latest?lang=yoruba"><img src="https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fbbc-api.vercel.app%2Flatest%3Flang%3Dyoruba&query=%24%5B'elapsed%20time'%5D&label=Latency"></a>

**Comment by smyja** [comment]
> @smyja, Thanks for your suggestion and letting me know! I've just committed changes on [`56af8dc`](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/commit/56af8dc7a20d444e638c1fe91fe7a3982961d4ac). From now on, you can use the BBC News API to get news in Yoruba. This endpoint will respond with news from [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba).
> 
> [![](https://camo.githubusercontent.com/b6c89cee7bef3d7c1954b3e5779b942799b4185295b4703aa14e00f2b965ac9f/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577733f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4e657773)](https://bbc-api.vercel.app/news?lang=yoruba) [![](https://camo.githubusercontent.com/3a7d62bdfc3155118ada11e286b95ea6d874aae8ff0f69239bc3320c84f56ee8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577732533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/news?lang=yoruba)
> 
> [![](https://camo.githubusercontent.com/e784e93e79e10559206508497c5b76c2a48c78eb831be3af623a701d0bad861d/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573743f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4c6174657374)](https://bbc-api.vercel.app/latest?lang=yoruba) [![](https://camo.githubusercontent.com/95db51c76ee9e4552ac72a10c62d0f7be8fef86215fa4e1077f9cbfb0db13526/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573742533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/latest?lang=yoruba)

Great, you should create a new release so people can upgrade.

**Comment by Sayad-Uddin-Tahsin** [comment]
> you

@smyja, What did you mean by `8k` though?

**Comment by Sayad-Uddin-Tahsin** [comment]
> > > > @smyja, Thanks for your suggestion and letting me know! I've just committed changes on [`56af8dc`](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/commit/56af8dc7a20d444e638c1fe91fe7a3982961d4ac). From now on, you can use the BBC News API to get news in Yoruba. This endpoint will respond with news from [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba).
> > > > [![](https://camo.githubusercontent.com/b6c89cee7bef3d7c1954b3e5779b942799b4185295b4703aa14e00f2b965ac9f/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577733f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4e657773)](https://bbc-api.vercel.app/news?lang=yoruba) [![](https://camo.githubusercontent.com/3a7d62bdfc3155118ada11e286b95ea6d874aae8ff0f69239bc3320c84f56ee8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577732533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/news?lang=yoruba)
> > > > [![](https://camo.githubusercontent.com/e784e93e79e10559206508497c5b76c2a48c78eb831be3af623a701d0bad861d/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573743f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4c6174657374)](https://bbc-api.vercel.app/latest?lang=yoruba) [![](https://camo.githubusercontent.com/95db51c76ee9e4552ac72a10c62d0f7be8fef86215fa4e1077f9cbfb0db13526/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573742533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/latest?lang=yoruba)
> > > 
> > > 
> > > Great, you should create a new release so people can upgrade. Also, how do you do paging? i need to scrape at least 8k
> > 
> > @smyja, What did you mean by `8k` though?
> 
> I meant 8,000 pages

Seems, [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba) has only 1 page! Where did the 8k pages come from?

**Comment by smyja** [comment]
> > > > > @smyja, Thanks for your suggestion and letting me know! I've just committed changes on [`56af8dc`](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/commit/56af8dc7a20d444e638c1fe91fe7a3982961d4ac). From now on, you can use the BBC News API to get news in Yoruba. This endpoint will respond with news from [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba).
> > > > > [![](https://camo.githubusercontent.com/b6c89cee7bef3d7c1954b3e5779b942799b4185295b4703aa14e00f2b965ac9f/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577733f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4e657773)](https://bbc-api.vercel.app/news?lang=yoruba) [![](https://camo.githubusercontent.com/3a7d62bdfc3155118ada11e286b95ea6d874aae8ff0f69239bc3320c84f56ee8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577732533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/news?lang=yoruba)
> > > > > [![](https://camo.githubusercontent.com/e784e93e79e10559206508497c5b76c2a48c78eb831be3af623a701d0bad861d/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573743f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4c6174657374)](https://bbc-api.vercel.app/latest?lang=yoruba) [![](https://camo.githubusercontent.com/95db51c76ee9e4552ac72a10c62d0f7be8fef86215fa4e1077f9cbfb0db13526/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573742533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/latest?lang=yoruba)
> > > > 
> > > > 
> > > > Great, you should create a new release so people can upgrade. Also, how do you do paging? i need to scrape at least 8k
> > > 
> > > 
> > > @smyja, What did you mean by `8k` though?
> > 
> > 
> > I meant 8,000 pages
> 
> Seems, [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba) has only 1 page! Where did the 8k page come from?

Categories/topics have more than 1 page. Here's one https://www.bbc.com/yoruba/topics/c340q0y3p5kt

**Comment by Sayad-Uddin-Tahsin** [comment]
> > > > > > @smyja, Thanks for your suggestion and letting me know! I've just committed changes on [`56af8dc`](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/commit/56af8dc7a20d444e638c1fe91fe7a3982961d4ac). From now on, you can use the BBC News API to get news in Yoruba. This endpoint will respond with news from [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba).
> > > > > > [![](https://camo.githubusercontent.com/b6c89cee7bef3d7c1954b3e5779b942799b4185295b4703aa14e00f2b965ac9f/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577733f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4e657773)](https://bbc-api.vercel.app/news?lang=yoruba) [![](https://camo.githubusercontent.com/3a7d62bdfc3155118ada11e286b95ea6d874aae8ff0f69239bc3320c84f56ee8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466e6577732533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/news?lang=yoruba)
> > > > > > [![](https://camo.githubusercontent.com/e784e93e79e10559206508497c5b76c2a48c78eb831be3af623a701d0bad861d/68747470733a2f2f696d672e736869656c64732e696f2f776562736974653f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573743f6c616e673d796f727562612675705f6d6573736167653d4f6e6c696e6526646f776e5f6d6573736167653d4f66666c696e65266c6162656c3d596f727562612f4c6174657374)](https://bbc-api.vercel.app/latest?lang=yoruba) [![](https://camo.githubusercontent.com/95db51c76ee9e4552ac72a10c62d0f7be8fef86215fa4e1077f9cbfb0db13526/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f75726c3d68747470732533412532462532466262632d6170692e76657263656c2e6170702532466c61746573742533466c616e67253344796f727562612671756572793d25323425354227656c617073656425323074696d6527253544266c6162656c3d4c6174656e6379)](https://bbc-api.vercel.app/latest?lang=yoruba)
> > > > > 
> > > > > 
> > > > > Great, you should create a new release so people can upgrade. Also, how do you do paging? i need to scrape at least 8k
> > > > 
> > > > 
> > > > @smyja, What did you mean by `8k` though?
> > > 
> > > 
> > > I meant 8,000 pages
> > 
> > Seems, [`https://www.bbc.com/yoruba`](https://www.bbc.com/yoruba) has only 1 page! Where did the 8k page come from?
> 
> Categories/topics have more than 1 page. Here's one https://www.bbc.com/yoruba/topics/c340q0y3p5kt

Oh, you meant that!? Actually BBC News API responds with the news from the main page (`https://www.bbc.com/yoruba`) as it is considered as latest and important! Though I beleive it is possible to respond with other pages news if wanted.
